### PR TITLE
[WIP] Feature validator

### PR DESCRIPTION
**Pull request by edisinovcic**
Current naive implementation of the validator. Implementation still needs to be discussed.

DO NOT MERGE!

### CODE REVIEW

**Comment by edisinovcic** [comment]
@cgewecke can you please try to test it locally, as when I remove JSON.parse on loadFiles level I can't seem to get positive results from this function: https://github.com/ethereum/source-verify/blob/03a6bf4a7b3a9cd3e2eea092732894f7a567d3b8/injector.js#L96

I'm using files from test/sources/all/simple.meta.json and Simple.sol

**Comment by cgewecke** [comment]
I read through the [relevant thread][1] about this at Solidity and it looks like the person wants to verify a contract on-chain by cloning a Truffle project on Github, compiling the contracts and checking if the metadata produced matches the hash of the bytecode deployed to chain. 

There are difficulties with this because of the way Truffle compiles using absolute paths as source keys - something discussed in #23, #24, and #27. I'm not sure this PR is really the validation they're looking for unfortunately ... 

Perhaps we should investigate this in more depth as part of a second iteration where we try to make a truffle plugin or general lib for cli tools that could handle this use case. 

[1]: https://gitter.im/ethereum/solidity?at=5e53c4a3fa9f20553b4a0e88

Reproducing part of the thread here for reference:
```
So here is how it works-:
I compiled contracts on my machine and deployed it on the chain. 
Which means metadata associated with the deployment is related to my machine
Now user wants to verify that the contract that they are going to interact with actually 
corresponds to our open source repository
1. They clone the repository
2 .They compile the contracts using their machine. Now in this case metadata will change
3. Now they verify both bytecodes

The verification process should work out of the box, irrespective of the machine and environment used for the actual compilation and deployment
Though the compiler version and other compiler settings should remain same
```

**Comment by edisinovcic** [comment]
I definitely agree. Let's keep it open and discuss it after ethcc to see how to solve this.

**Comment by edisinovcic** [comment]
This was merged by mistake :( @cgewecke should I remove it from staging?

**Comment by cgewecke** [comment]
@edisinovcic I undid it in an earlier rebase it's all fine :)

**Comment by edisinovcic** [comment]
Awesome, tnx!

**Comment by aaronmboyd** [comment]
> I definitely agree. Let's keep it open and discuss it after ethcc to see how to solve this.

Is there a solution for this?

**Pull request merged**
