### PR TITLE
Feature cd

### PR DESCRIPTION
**Pull request by edisinovcic**
CD part is ready.

https://circleci.com/gh/ethereum/source-verify/264

### CODE REVIEW

**Comment by edisinovcic** [comment]
@cgewecke Should I merge this and than you can update it in repo-reorg (moving deploy to scripts, updating circleci config) or do you want me to do it now?

**Comment by cgewecke** [comment]
@edisinovcic This LGTM - the only thing I see is that it looks like this branch might have been created off of `feature-validator` rather than `staging`... do you want those additional changes in?

**Comment by cgewecke** [comment]
> you can update it in repo-reorg (moving deploy to scripts, updating circleci config)

Yes I can rebase it .. no worries.

**Comment by edisinovcic** [comment]
Okay, tnx, merging.

**Pull request merged**
