### PR TITLE
Update README for PoC2 

### PR DESCRIPTION
**Pull request by cgewecke**
+ Rewrites the README, describing source verify as a service, with a website and monitor. 
+ Adds sources / address for simple examples deployed to Ropsten which the UI can recompile.

 Solves: https://github.com/ethereum/source-verify/pull/69

### CODE REVIEW

**Comment by cgewecke** [comment]
Re-targeted to `staging` per code freeze on master.

**Comment by edisinovcic** [comment]
@cgewecke I've also added images to this for repository so it's a bit more of a visual explainer for the users in the future. And feel free to target master branch.

**Comment by edisinovcic** [comment]
@cgewecke I've update README with images and functionalities of Repository and also have updated description of docker-compose on how to build it and run it. Please take a look at it and feel free to merge afterward. Also https://github.com/ethereum/source-verify/pull/75 PR afterwards.

**Comment by cgewecke** [comment]
@edisinovcic Ok great, lgtm. I'm going to open an issue about re-structuring the README into some smaller components / sub-files in a docs folder because it's getting kind of large. 

Maybe we could start organizing things so they can be migrated to a ReadTheDocs at some point.

**Pull request merged**
